// Generated by CoffeeScript 1.6.3
(function() {
  var match, minimatch, parseCommaSeparatedAndRemoveBlanks, termColor, termColorWrap,
    __slice = [].slice;

  this.parseArgs = function(raw) {
    var arg, command, except, first, only;
    first = raw[0];
    if (match(first, '--help', '-h')) {
      return {
        help: true
      };
    }
    if (match(first, '--version', '-v')) {
      return {
        version: true
      };
    }
    command = [];
    only = [];
    except = [];
    raw = raw.slice();
    while (arg = raw.shift()) {
      switch (arg) {
        case '--only':
        case '-o':
          only = parseCommaSeparatedAndRemoveBlanks(raw.shift());
          break;
        case '--except':
        case '-e':
          except = parseCommaSeparatedAndRemoveBlanks(raw.shift());
          break;
        default:
          command.push(arg);
      }
    }
    command = command.length !== 0 ? command.join(' ') : null;
    return {
      command: command,
      only: only,
      except: except
    };
  };

  parseCommaSeparatedAndRemoveBlanks = function(str) {
    var i, _i, _len, _ref, _results;
    _ref = str.split(',');
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      i = _ref[_i];
      if (i !== '') {
        _results.push(i);
      }
    }
    return _results;
  };

  match = function() {
    var val, values;
    val = arguments[0], values = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    return values.indexOf(val) >= 0;
  };

  this.log = function() {
    var args;
    args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    return console.log.apply(console, args);
  };

  this.log.info = function(msg) {
    return console.error(termColorWrap('0;38;5;246', "- " + msg));
  };

  termColorWrap = function(code, str) {
    return termColor(code) + str + termColor();
  };

  termColor = function(code) {
    if (code == null) {
      code = '';
    }
    return '\x1B' + '[' + code + 'm';
  };

  minimatch = require('minimatch');

  this.matchesGlobs = function(path, globs) {
    var glob, matches;
    matches = (function() {
      var _i, _len, _results;
      _results = [];
      for (_i = 0, _len = globs.length; _i < _len; _i++) {
        glob = globs[_i];
        if (minimatch(path, glob)) {
          _results.push(match);
        }
      }
      return _results;
    })();
    return matches.length !== 0;
  };

  this.localTime = function() {
    return (new Date).toTimeString().split(' ')[0];
  };

  this.exit = function(status, message) {
    if (message != null) {
      console.log(message);
    }
    return process.exit(status);
  };

  this.npmVersion = function() {
    return JSON.parse(require('fs').readFileSync(__dirname + '/../package.json')).version;
  };

}).call(this);
