// Generated by CoffeeScript 1.6.3
(function() {
  var parseData, spawn;

  spawn = require('child_process').spawn;

  module.exports = function(dir, callback) {
    var watcherProcess;
    watcherProcess = spawn(__dirname + '/../node_modules/.bin/wachdir', [dir]);
    watcherProcess.stdout.on('data', function(data) {
      var path, _i, _len, _ref, _results;
      _ref = parseData(data.toString());
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        path = _ref[_i];
        _results.push(callback(path));
      }
      return _results;
    });
    return watcherProcess.on('exit', function(code) {
      return process.stderr.write(("Unable to start watcher for \"" + dir + "\".\nThis is probably a bug.") + '\n');
    });
  };

  parseData = function(str) {
    return str.split('\n').slice(0, -1);
  };

}).call(this);
