// Generated by CoffeeScript 1.6.3
(function() {
  var exit, fs, localTime, log, matchesGlobs, npmVersion, parseArgs, path, spawn, usage, watch, _ref;

  path = require('path');

  fs = require('fs');

  spawn = require('child_process').spawn;

  _ref = require('./support'), parseArgs = _ref.parseArgs, log = _ref.log, matchesGlobs = _ref.matchesGlobs, localTime = _ref.localTime, exit = _ref.exit, npmVersion = _ref.npmVersion;

  watch = require('./wach');

  this.run = function(rawArgs) {
    var args, child, cwd, diedOnItsOwn, runCommand, shouldRestart;
    args = parseArgs(rawArgs);
    if (args.help != null) {
      exit(0, usage);
    }
    if (args.version != null) {
      exit(0, npmVersion());
    }
    if (args.command == null) {
      exit(1, usage);
    }
    log.info("Will kill and restart: " + args.command);
    if (args.only.length === 0) {
      log.info("when any files added or updated");
    } else {
      log.info("when files matching {" + (args.only.join(',')) + "} added or updated");
    }
    if (args.except.length !== 0) {
      log.info("except those matching {" + (args.except.join(',')) + "}");
    }
    child = null;
    shouldRestart = false;
    diedOnItsOwn = false;
    runCommand = function() {
      log.info("starting ...");
      child = spawn('sh', ['-c', "exec " + args.command]);
      child.stdout.pipe(process.stdout);
      child.stderr.pipe(process.stderr);
      return child.on('exit', function(code) {
        if (shouldRestart) {
          log.info("killed");
          runCommand();
          return shouldRestart = false;
        } else {
          log.info("process exited by itself, crash?");
          return diedOnItsOwn = true;
        }
      });
    };
    runCommand();
    cwd = process.cwd();
    return watch(cwd, function(changedPath) {
      changedPath = path.relative(cwd, changedPath);
      if (!fs.existsSync(changedPath)) {
        return;
      }
      if ((args.only.length !== 0) && (!matchesGlobs(changedPath, args.only))) {
        return;
      }
      if ((args.except.length !== 0) && (matchesGlobs(changedPath, args.except))) {
        return;
      }
      shouldRestart = true;
      log.info("");
      log.info("changed: " + changedPath + " (" + (localTime()) + ")");
      log.info("killin ...");
      child.kill();
      if (diedOnItsOwn) {
        runCommand();
        return diedOnItsOwn = false;
      }
    });
  };

  usage = "The \"server\" version of `wach`. Pass it a command to start a long running\nprocess (such as a web server) and it will run that process then monitor\nthe current directory for file modifications. When a file changes it will\nautomatically restart the process.\n\nUsage:\n  wachs [options] <command>\n\nRequired:\n  <command>\n    The command to restart every time an update occurs in the directory being monitored.\n\nOptions:\n  -o|--only <globs>\n    Only run <command> when the path that changed matches <globs>.\n\n  -e|--except <globs>\n    Only run <command> when the path that changed doesn't match <globs>.\n\n  Quote the <globs> (\"*.c\") or add a trailing comma (*.c,) to prevent your shell from\n  automatically expanding  them.\n\nExamples:\n  wachs node server.js\n  wachs coffee server.coffee\n  wachs ruby sinatra-app.rb\n  wachs -o server/*.js, node server.js";

}).call(this);
